name: fitapp
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2+1
  image_picker: 0.4.1
  firebase_storage: 1.0.4
  firebase_auth: 0.6.2+1
  google_sign_in: ^3.2.1
  uuid: 1.0.3
  image: 2.0.4
  path_provider: 0.4.1
  font_awesome_flutter: 8.0.1
  async: "^2.0.4"
  http: "^0.12.0"
  shared_preferences: "^0.4.1"
  cached_network_image: "^0.5.0"
  firebase_messaging: ^2.0.2
  location: ^1.4.1
  geocoder: ^0.1.1
  nima: ^1.0.0
  flutter_pedometer: ^0.9.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf


  assets:
    - assets/images/google_signin_button.png
    - assets/Flexer.nma
    - assets/Flexer.png
    - assets/flexin.nma
    - assets/flexin.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
